[package]
name = "mnist-neural-network"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.3"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
csv = "1.1.6"